add style for the filter + fix import
WildCodeSchool/2022-09-JS-Reims-project-2-find-fuel pull request #10
Opened 2022-10-21 08:15 UTC by M-Valentin-51

2022-10-21 08:43 UTC, rocambille requested changes

2022-10-21 08:43 UTC, rocambille commented on frontend/src/components/filter/Filter.jsx
> +    <div className="contenerFilter">
container, not contener

2022-10-21 08:43 UTC, rocambille commented
conflicts to resolve

2022-10-26 07:58 UTC, Justine-Merlin requested changes

2022-10-26 07:58 UTC, Justine-Merlin commented on frontend/src/App.css
> +
Delete blank line.

2022-10-26 07:58 UTC, Justine-Merlin commented on frontend/style/filter.css
> +.contenerFilter{
Classname in your jsx component might be containerFilter.

2022-10-26 07:58 UTC, Justine-Merlin commented on frontend/style/filter.css
> +
Delete blank line.

2022-10-27 07:35 UTC, merged